[project]
name = "ecomm-prod-assistant"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "langchain>=1.2.9",
    "langchain-core>=1.2.9",
    "python-dotenv>=1.2.1",
    "streamlit>=1.54.0",
]
